# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weeklog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('weeknum', models.IntegerField()),
                ('week_beginning', models.DateField()),
                ('primary_city_during_week', models.CharField(max_length=150)),
                ('primary_city_weekend', models.CharField(max_length=150)),
                ('notes', models.TextField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
