# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeknotes', '0002_auto_20161130_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklog',
            name='weeknum',
            field=models.IntegerField(blank=True, null=True, verbose_name='leave blank'),
        ),
        migrations.AlterField(
            model_name='weeklog',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='ok to leave blank'),
        ),
    ]
