# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-01 01:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeknotes', '0003_auto_20161130_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklog',
            name='weeknum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='weeklog',
            name='year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
