# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weeknotes', '0004_auto_20161130_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklog',
            name='notes',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
