# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=125)),
                ('group_description', models.TextField(max_length=300, null=True)),
                ('group_imp_rating', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3')], max_length=1, null=True)),
                ('group_strategy', models.TextField(max_length=500, null=True)),
                ('target_contact_cycle_weeks', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
