# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_groups', '0004_auto_20161128_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_imp_rating',
            field=models.CharField(choices=[('1', 'extremely important'), ('2', 'very important'), ('3', 'medium importance'), ('4', 'low importance')], default=3, max_length=24),
            preserve_default=False,
        ),
    ]
