# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 04:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_groups', '0005_auto_20161128_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_imp_rating',
            field=models.CharField(choices=[('1', 'extremely important'), ('2', 'important'), ('3', 'medium importance'), ('4', 'low importance')], max_length=24),
        ),
    ]
