# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_groups', '0007_auto_20161128_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='group_imp_rating',
            field=models.CharField(choices=[('v high', 'v high'), ('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=24),
        ),
    ]
