# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-19 02:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('met_where', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=500, null=True)),
                ('city', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.CharField(blank=True, max_length=120, null=True)),
                ('phone', models.CharField(blank=True, max_length=120, null=True)),
                ('workplace', models.CharField(blank=True, max_length=120, null=True)),
                ('ind_imp_rating', models.IntegerField(blank=True, null=True)),
                ('first_met', models.DateField(null=True)),
                ('added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
