# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_master_primary_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='next_contact_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
