# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_auto_20161120_1733'),
        ('master', '0004_master_next_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='tag1',
            field=models.ManyToManyField(to='tags.Tag'),
        ),
    ]
