# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0005_master_tag1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='notes',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
