# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-25 00:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0010_auto_20161124_2358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='first_met',
            field=models.DateField(blank=True, default=datetime.date(2016, 11, 25), null=True),
        ),
    ]
