# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-26 05:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0012_master_starred'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='dont_update_next_contact_date',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='master',
            name='prospect',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='master',
            name='first_met',
            field=models.DateField(blank=True, default=datetime.date(2016, 11, 26), null=True),
        ),
    ]
