# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0016_auto_20161128_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='ind_imp_rating',
            field=models.CharField(blank=True, choices=[('1', 'extremely important'), ('2', 'important'), ('3', 'medium importance'), ('4', 'low importance')], max_length=24, null=True),
        ),
        migrations.DeleteModel(
            name='Importance',
        ),
    ]
