# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-29 05:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0017_auto_20161128_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='ind_imp_rating',
            field=models.CharField(blank=True, choices=[('extremely important', 'extremely important'), ('important', 'important'), ('medium importance', 'medium importance'), ('low importance', 'low importance')], max_length=24, null=True),
        ),
    ]
