# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0021_auto_20161130_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='first_met',
            field=models.DateField(blank=True, default=datetime.date.today, null=True),
        ),
    ]
