# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-24 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0022_auto_20161206_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='master',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
