# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-20 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=150)),
                ('tag_description', models.CharField(max_length=400)),
                ('tag_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
