# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_auto_20161124_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_log',
            name='contact_notes',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
