# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-07 05:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0009_auto_20161130_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_log',
            name='contact_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
