# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-09 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0010_auto_20161206_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_log',
            name='contact_notes',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
